version: '3'

services:
  db:
    container_name: database
    image: postgres:alpine
    env_file:
      .env
    volumes:
      - ./postgres_data:/var/lib/postgresq/data
    ports:
      - '5432:5432'
    networks:
      - app-network
  backend:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports: 
      - '5000:5000'
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - ./backend:/backend
    networks:
      - app-network
  frontend:
    container_name: web
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports: 
      - '3000:3000'
    depends_on:
      - db
      - backend
    volumes:
      - ./frontend:/frontend
    networks:
      - app-network
  
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge